name: turbostarter

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-turbostarter}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-turbostarter}
      POSTGRES_DB: ${POSTGRES_DB:-core}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-turbostarter}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
