packages:
  - "apps/*"
  - "packages/**"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.638
  "@trpc/react-query": ^11.0.0-rc.638
  "@trpc/server": ^11.0.0-rc.638
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: 5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.12
    "@types/react-dom": 18.3.1
