packages:
  - "apps/*"
  - "packages/**"
  - "tooling/*"

catalog:
  "@tanstack/react-query": 5.62.2
  "@trpc/client": ^11.0.0-rc.657
  "@trpc/react-query": ^11.0.0-rc.657
  "@trpc/server": ^11.0.0-rc.657
  eslint: 9.16.0
  prettier: 3.3.3
  typescript: 5.7.2
  zod: 3.23.8

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0
