packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  "@tanstack/react-query": 5.81.5
  envin: 1.1.8
  eslint: 9.30.1
  prettier: 3.6.2
  typescript: 5.8.3
  zod: 4.0.17
  react-native: 0.79.5

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.1.6
    "@types/react-dom": 19.1.5
  node22:
    "@types/node": 22.16.0
