packages:
  - "apps/*"
  - "packages/**"
  - "tooling/*"

catalog:
  "@tanstack/react-query": 5.74.4
  "@t3-oss/env-core": 0.13.0
  eslint: 9.16.0
  prettier: 3.5.3
  typescript: 5.7.2
  zod: 3.24.1
  react-native: 0.76.7

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0
