project_id = "turbostarter"

[api]
port = 54321
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
jwt_expiry = 86400 # 24 hours
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
additional_redirect_urls = ["http://localhost:54321/auth/v1/callback", "turbostarter://**"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirm email"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your link to login"
content_path = "./supabase/templates/magic_link.html"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[inbucket]
enabled = true

[realtime]
enabled = false

[storage]
enabled = false

[analytics]
enabled = false
