name: turbostarter

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-turbostarter}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-turbostarter}
      POSTGRES_DB: ${POSTGRES_DB:-core}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
