name: "CI / Setup db"
description: "Common setup steps for publishing database changes"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "20.x"

runs:
  using: "composite"
  steps:
    - name: ✅ Checkout code
      uses: actions/checkout@v4

    - name: 💾 Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: CI / Tests
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

      - name: 🔨 Setup
        uses: ../setup
        with:
          node-version: ${{ inputs.node-version }}

      - name: ⚡ Setup Supabase CLI
        uses: supabase/setup-cli@v1
